### ISSUE TITLE
Exception in InvalidValue->inspect()

### ISSUE THREAD

**Issue by franksl** [swaggest/php-json-schema#27]
Hello,
I'm testing the new 0.10.3 error handling features.
I have a complex schema that is split on multiple files.
I make use of the Preloaded class to convert "file://" urls to sub-schema contents.
When using the inspect method I get an error when using these references.
For example I defined a Preloaded like this:
```
$refProvider = new Preloaded();
$refProvider->setSchemaData(
    'file://baseTypes.json',
    json_decode(file_get_contents('/schema/baseTypes.json'))
);
```

And used in a schema like this:
```
{
    "$schema": "http://json-schema.org/schema#",
    "type": "object",
    "properties": {
        "actions": { "$ref": "file://baseTypes.json#/actionList" }
    },
    "required": ["actions"],
    "additionalProperties": false
}
```

When I force an error the inspect method returns an exception:
```
PHP Fatal error:  Uncaught Swaggest\JsonDiff\Exception: Path must start with "/": fil in /var/www/html/testjsonschema/vendor/swaggest/json-diff/src/JsonPointer.php:35
Stack trace:
#0 /var/www/html/testjsonschema/vendor/swaggest/json-schema/src/Path/PointerUtil.php(81): Swaggest\JsonDiff\JsonPointer::splitPath('fil')
#1 /var/www/html/testjsonschema/vendor/swaggest/json-schema/src/Path/PointerUtil.php(42): Swaggest\JsonSchema\Path\PointerUtil::rebuildPointer('fil', false)
#2 /var/www/html/testjsonschema/vendor/swaggest/json-schema/src/InvalidValue.php(33): Swaggest\JsonSchema\Path\PointerUtil::getSchemaPointers('#->properties:a...')
#3 /var/www/html/testjsonschema/test.php(39): Swaggest\JsonSchema\InvalidValue->inspect()
#4 {main}
  thrown in /var/www/html/testjsonschema/vendor/swaggest/json-diff/src/JsonPointer.php on line 35
```

In this case $error->processingPath (used in INvalidValue, row 33) contains:
```
#->properties:actions->$ref[file://baseTypes.json#/actionList]->patternProperties[^[a-zA-Z0-9_]+$]:dsDocSof
```

Thanks,
Frank

**Comment by vearutop** [comment]
please try `v0.10.4`
